
def zone_to_zonekey(zone: str) -> str | None:
    if zone:
        return zone_aliases.get(zone.lower(), zone.lower())


def zonekey_to_zone(zonekey: str) -> str | None:
    if zonekey:
        return capitalize(zonekey_to_alias.get(zonekey, zonekey))


def capitalize(string: str) -> str:
    return " ".join(map(str.capitalize, string.split()))


zone_aliases_who = {
    "kael drakkal": "kael",
    "eastern wastes": "eastwastes",
    "the wakening land": "wakening",
    "siren's grotto": "sirens",
    "the plane of hate": "hateplane",
    "burning woods": "burningwood",
    "south ro": "sro",
    "plane of sky": "airplane",
    "south karana": "southkarana",
    "sleeper's tomb": "sleeper",
    "mountains of rathe": "rathemtn",
    "nektulos forest": "nektulos",
    "city of mist": "citymist",
    "west cabilis": "cabwest",
    "east cabilis": "cabeast",
    "cazic-thule": "cazicthule",
    "everfrost peaks": "everfrost",
    "highkeep": "highkeep",
    "kithicor forest": "kithicor",
    "lower guk": "gukbottom",
    "north ro": "nro",
    "north karana": "northkarana",
    "permafrost keep": "permafrost",
    "clan runnyeye": "runnyeye",
    "the ruins of old paineel": "hole",
    "the warrens": "warrens",
    "thurgadin": "thurgadina",
    "upper guk": "guktop",
    "warsliks wood": "warslikswood",
    "west karana": "qey2hh1",
    "clan crushbone": "crushbone",
    "east karana": "eastkarana",
    "the field of bone": "fieldofbone",
    "qeynos catacombs": "qcat",
}

zone_aliases_zone = {
    "ocean of tears": "oot",
    "northern plains of karana": "northkarana",
    "skyshrine": "skyshrine",
    "the nektulos forest": "nektulos",
    "sleepers tomb": "sleeper",
    "erudin": "erudnext",
    "kedge keep": "kedge",
    "ak'anon": "akanon",
    "warsliks woods": "warslikswood",
    "castle mistmoore": "mistmoore",
    "high keep": "highkeep",
    "highpass hold": "highpass",
    "qeynos aqueduct system": "qcat",
    "lake of ill omen": "lakeofillomen",
    "kael drakkel": "kael",
    "tower of frozen shadow": "frozenshadow",
    "icewell keep": "thurgadinb",
    "the feerrott": "feerrott",
    "ruins of sebilis": "sebilis",
    "old sebilis": "sebilis",
    "east commonlands": "ecommons",
    "cabilis east": "cabeast",
    "veeshan's peak": "veeshan",
    "surefall glade": "qrg",
    "innothule swamp": "innothule",
    "halas": "halas",
    "solusek's eye": "soldunga",
    "estate of unrest": "unrest",
    "blackburrow": "blackburrow",
    "gorge of king xorbb": "beholder",
    "plane of hate": "hateplane",
    "west commonlands": "commons",
    "north qeynos": "qeynos2",
    "cobalt scar": "cobaltscar",
    "befallen": "befallen",
    "paineel": "paineel",
    "north freeport": "freportn",
    "nagafen's lair": "soldungb",
    "runnyeye citadel": "runnyeye",
    "frontier mountains": "frontiermtns",
    "the city of mist": "citymist",
    "west freeport": "freportw",
    "butcherblock mountains": "butcher",
    "permafrost caverns": "permafrost",
    "the hole": "hole",
    "qeynos hills": "qeytoqrg",
    "arena": "arena",
    "lavastorm mountains": "lavastorm",
    "plane of growth": "growthplane",
    "misty thicket": "misty",
    "city of thurgadin": "thurgadina",
    "northern desert of ro": "nro",
    "neriak foreign quarter": "neriaka",
    "infected paw": "paw",
    "plane of air": "airplane",
    "southern felwithe": "felwitheb",
    "velketor's labyrinth": "velketor",
    "cabilis west": "cabwest",
    "lake rathetear": "lakerathe",
    "kurn's tower": "kurn",
    "dagnor's cauldron": "cauldron",
    "western wastes": "westwastes",
    "temple of veeshan": "templeveeshan",
    "lesser faydark": "lfaydark",
    "everfrost": "everfrost",
    "trakanon's teeth": "trakanon",
    "eastern plains of karana": "eastkarana",
    "north kaladim": "kaladimb",
    "dreadlands": "dreadlands",
    "south qeynos": "qeynos",
    "plane of fear": "fearplane",
    "rathe mountains": "rathemtn",
    "the wakening lands": "wakening",
    "southern desert of ro": "sro",
    "the burning wood": "burningwood",
    "greater faydark": "gfaydark",
    "dragon necropolis": "necropolis",
    "guk": "guktop",
    "the overthere": "overthere",
    "eastern wastelands": "eastwastes",
    "field of bone": "fieldofbone",
    "neriak third gate": "neriakc",
    "erud's crossing": "erudsxing",
    "northern felwithe": "felwithea",
    "firiona vie": "firiona",
    "east freeport": "freporte",
    "swamp of no hope": "swampofnohope",
    "timorous deep": "timorous",
    "dalnir": "dalnir",
    "southern plains of karana": "southkarana",
    "western plains of karana": "qey2hh1",
    "skyfire mountains": "skyfire",
    "mines of nurga": "nurga",
    "oasis of marr": "oasis",
    "the emerald jungle": "emeraldjungle",
    "great divide": "greatdivide",
    "sirens grotto": "sirens",
    "erudin palace": "erudnint",
    "toxxulia forest": "tox",
    "ruins of old guk": "gukbottom",
    "steamfont mountains": "steamfont",
    "south kaladim": "kaladima",
    "najena": "najena",
    "stonebrunt mountains": "stonebrunt",
    "howling stones": "charasis",
    "kerra isle": "kerraridge",
    "lost temple of cazic-thule": "cazicthule",
    "neriak commons": "neriakb",
    "karnor's castle": "karnor",
    "crystal caverns": "crystal",
    "iceclad ocean": "iceclad",
    "warrens": "warrens",
    "oggok": "oggok",
    "grobb": "grobb",
    "rivervale": "rivervale",
    "plane of mischief": "mischiefplane",
    "kaesora": "kaesora",
    "temple of droga": "droga",
    "crushbone": "crushbone",
    "chardok": "chardok",
    "kithicor woods": "kithicor",
    "temple of solusek ro": "soltemple",
}

zone_aliases = zone_aliases_zone | zone_aliases_who
zonekey_to_alias = {v: k for k, v in zone_aliases.items()}
